version: "3.2"
services:
  zookeeper1:
    hostname: zookeeper1
    image: zookeeper  
#wurstmeister/zookeeper:latest

##    networks:
##      zookeeper-kafka-net:
##        ipv4_address: 10.1.3.71
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    restart: always

  zookeeper2:
    hostname: zookeeper2
    image: zookeeper
# wurstmeister/zookeeper:latest
##    networks:
##      zookeeper-kafka-net:
##        ipv4_address: 10.1.3.72
    ports:
      - 22181:2181
      - "22888:2888"
      - "23888:3888"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    restart: always

  zookeeper3:
    hostname: zookeeper3
    image: zookeeper
# wurstmeister/zookeeper:latest
##    networks:
##      zookeeper-kafka-net:
##        ipv4_address: 10.1.3.73
    ports:
      - 32181:2181
      - "32888:2888"
      - "33888:3888"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    restart: always


